// Guest-only drawing fixture. Studio row selection must never run this command.
menu(title='Renderer fixture')
{
    item(title='&Normal && 日本語' cmd='cmd.exe' args='/c echo unexpected>C:\QweShellEvidence\unexpected-command.txt')
    item(title='Checked' checked=1 cmd='cmd.exe' args='/c exit 19')
    item(title='Disabled' vis=2 cmd='cmd.exe' args='/c exit 19')
    item(title='Icon' image=[\uE149, #22A7F2] cmd='cmd.exe' args='/c exit 19')
    item(title='After separator' sep='before' cmd='cmd.exe' args='/c exit 19')
}

menu(title='Renderer scroll')
{
    item(title='Scroll row 01' cmd='cmd.exe' args='/c exit 19')
    item(title='Scroll row 02' cmd='cmd.exe' args='/c exit 19')
    item(title='Scroll row 03' cmd='cmd.exe' args='/c exit 19')
    item(title='Scroll row 04' cmd='cmd.exe' args='/c exit 19')
    item(title='Scroll row 05' cmd='cmd.exe' args='/c exit 19')
    item(title='Scroll row 06' cmd='cmd.exe' args='/c exit 19')
    item(title='Scroll row 07' cmd='cmd.exe' args='/c exit 19')
    item(title='Scroll row 08' cmd='cmd.exe' args='/c exit 19')
    item(title='Scroll row 09' cmd='cmd.exe' args='/c exit 19')
    item(title='Scroll row 10' cmd='cmd.exe' args='/c exit 19')
    item(title='Scroll row 11' cmd='cmd.exe' args='/c exit 19')
    item(title='Scroll row 12' cmd='cmd.exe' args='/c exit 19')
    item(title='Scroll row 13' cmd='cmd.exe' args='/c exit 19')
    item(title='Scroll row 14' cmd='cmd.exe' args='/c exit 19')
    item(title='Scroll row 15' cmd='cmd.exe' args='/c exit 19')
    item(title='Scroll row 16' cmd='cmd.exe' args='/c exit 19')
    item(title='Scroll row 17' cmd='cmd.exe' args='/c exit 19')
    item(title='Scroll row 18' cmd='cmd.exe' args='/c exit 19')
    item(title='Scroll row 19' cmd='cmd.exe' args='/c exit 19')
    item(title='Scroll row 20' cmd='cmd.exe' args='/c exit 19')
    item(title='Scroll row 21' cmd='cmd.exe' args='/c exit 19')
    item(title='Scroll row 22' cmd='cmd.exe' args='/c exit 19')
    item(title='Scroll row 23' cmd='cmd.exe' args='/c exit 19')
    item(title='Scroll row 24' cmd='cmd.exe' args='/c exit 19')
    item(title='Scroll row 25' cmd='cmd.exe' args='/c exit 19')
    item(title='Scroll row 26' cmd='cmd.exe' args='/c exit 19')
    item(title='Scroll row 27' cmd='cmd.exe' args='/c exit 19')
    item(title='Scroll row 28' cmd='cmd.exe' args='/c exit 19')
    item(title='Scroll row 29' cmd='cmd.exe' args='/c exit 19')
    item(title='Scroll row 30' cmd='cmd.exe' args='/c exit 19')
    item(title='Scroll row 31' cmd='cmd.exe' args='/c exit 19')
    item(title='Scroll row 32' cmd='cmd.exe' args='/c exit 19')
    item(title='Scroll row 33' cmd='cmd.exe' args='/c exit 19')
    item(title='Scroll row 34' cmd='cmd.exe' args='/c exit 19')
    item(title='Scroll row 35' cmd='cmd.exe' args='/c exit 19')
    item(title='Scroll row 36' cmd='cmd.exe' args='/c exit 19')
    item(title='Scroll row 37' cmd='cmd.exe' args='/c exit 19')
    item(title='Scroll row 38' cmd='cmd.exe' args='/c exit 19')
    item(title='Scroll row 39' cmd='cmd.exe' args='/c exit 19')
    item(title='Scroll row 40' cmd='cmd.exe' args='/c exit 19')
    item(title='Scroll row 41' cmd='cmd.exe' args='/c exit 19')
    item(title='Scroll row 42' cmd='cmd.exe' args='/c exit 19')
    item(title='Scroll row 43' cmd='cmd.exe' args='/c exit 19')
    item(title='Scroll row 44' cmd='cmd.exe' args='/c exit 19')
    item(title='Scroll row 45' cmd='cmd.exe' args='/c exit 19')
    item(title='Scroll row 46' cmd='cmd.exe' args='/c exit 19')
    item(title='Scroll row 47' cmd='cmd.exe' args='/c exit 19')
    item(title='Scroll row 48' cmd='cmd.exe' args='/c exit 19')
    item(title='Scroll row 49' cmd='cmd.exe' args='/c exit 19')
    item(title='Scroll row 50' cmd='cmd.exe' args='/c exit 19')
    item(title='Scroll row 51' cmd='cmd.exe' args='/c exit 19')
    item(title='Scroll row 52' cmd='cmd.exe' args='/c exit 19')
    item(title='Scroll row 53' cmd='cmd.exe' args='/c exit 19')
    item(title='Scroll row 54' cmd='cmd.exe' args='/c exit 19')
    item(title='Scroll row 55' cmd='cmd.exe' args='/c exit 19')
    item(title='Scroll row 56' cmd='cmd.exe' args='/c exit 19')
    item(title='Scroll row 57' cmd='cmd.exe' args='/c exit 19')
    item(title='Scroll row 58' cmd='cmd.exe' args='/c exit 19')
    item(title='Scroll row 59' cmd='cmd.exe' args='/c exit 19')
    item(title='Scroll row 60' cmd='cmd.exe' args='/c exit 19')
    item(title='Scroll row 61' cmd='cmd.exe' args='/c exit 19')
    item(title='Scroll row 62' cmd='cmd.exe' args='/c exit 19')
    item(title='Scroll row 63' cmd='cmd.exe' args='/c exit 19')
    item(title='Scroll row 64' cmd='cmd.exe' args='/c exit 19')
    item(title='Scroll row 65' cmd='cmd.exe' args='/c exit 19')
    item(title='Scroll row 66' cmd='cmd.exe' args='/c exit 19')
    item(title='Scroll row 67' cmd='cmd.exe' args='/c exit 19')
    item(title='Scroll row 68' cmd='cmd.exe' args='/c exit 19')
    item(title='Scroll row 69' cmd='cmd.exe' args='/c exit 19')
    item(title='Scroll row 70' cmd='cmd.exe' args='/c exit 19')
    item(title='Scroll row 71' cmd='cmd.exe' args='/c exit 19')
    item(title='Scroll row 72' cmd='cmd.exe' args='/c exit 19')
    item(title='Scroll row 73' cmd='cmd.exe' args='/c exit 19')
    item(title='Scroll row 74' cmd='cmd.exe' args='/c exit 19')
    item(title='Scroll row 75' cmd='cmd.exe' args='/c exit 19')
    item(title='Scroll row 76' cmd='cmd.exe' args='/c exit 19')
    item(title='Scroll row 77' cmd='cmd.exe' args='/c exit 19')
    item(title='Scroll row 78' cmd='cmd.exe' args='/c exit 19')
    item(title='Scroll row 79' cmd='cmd.exe' args='/c exit 19')
    item(title='Scroll row 80' cmd='cmd.exe' args='/c exit 19')
    item(title='Scroll row 81' cmd='cmd.exe' args='/c exit 19')
    item(title='Scroll row 82' cmd='cmd.exe' args='/c exit 19')
    item(title='Scroll row 83' cmd='cmd.exe' args='/c exit 19')
    item(title='Scroll row 84' cmd='cmd.exe' args='/c exit 19')
    item(title='Scroll row 85' cmd='cmd.exe' args='/c exit 19')
    item(title='Scroll row 86' cmd='cmd.exe' args='/c exit 19')
    item(title='Scroll row 87' cmd='cmd.exe' args='/c exit 19')
    item(title='Scroll row 88' cmd='cmd.exe' args='/c exit 19')
    item(title='Scroll row 89' cmd='cmd.exe' args='/c exit 19')
    item(title='Scroll row 90' cmd='cmd.exe' args='/c exit 19')
}
